# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/

sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.10'
  - '0.11'
  - '0.12'
branches:
  only:
    - /^v\d\.\d\.\d/    # only build tagged versions (rather than EVERY push)
    - /^PR /            # also build pull requests
after_success:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
