# AppVeyor Config
# http://www.appveyor.com/docs/lang/nodejs-iojs

environment:
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"

skip_tags: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run mocha

# Don't run MSBuild
build: off
